"""
Post-process norm_stats.json: clamp narrow quantile ranges.

This script reads an existing norm_stats.json (generated by compute_norm_stats.py),
detects dimensions where q99-q01 is too narrow (near-constant dims), and expands
the range to a configurable minimum. This prevents catastrophic amplification in
quantile normalization without modifying the upstream OpenPI transforms code.

Usage:
    python scripts/postprocess_norm_stats.py \
        --input  assets/pi05_aloha_wbcd_lora/pipeline_ab/A/norm_stats.json \
        --output assets/pi05_aloha_wbcd_lora/pipeline_ab/A/norm_stats.json \
        --min-range 0.1

The script will:
1. Load the norm_stats.json
2. For each dimension of each key, check if q99 - q01 < min_range
3. If so, expand q01/q99 symmetrically around the midpoint to achieve min_range
4. Save the result (can overwrite in-place or to a new file)
"""

import argparse
import json
import copy


def postprocess_norm_stats(norm_stats: dict, min_range: float = 0.1) -> tuple[dict, list[str]]:
    """Clamp narrow quantile ranges in norm_stats.

    For each dimension where q99 - q01 < min_range, expand q01 and q99
    symmetrically around their midpoint so that q99 - q01 == min_range.

    Returns:
        (modified_norm_stats, log_messages)
    """
    result = copy.deepcopy(norm_stats)
    logs = []

    for key, stats in result.items():
        q01 = stats.get("q01")
        q99 = stats.get("q99")
        if q01 is None or q99 is None:
            continue

        for i in range(len(q01)):
            raw_range = q99[i] - q01[i]
            if raw_range < min_range:
                mid = (q01[i] + q99[i]) / 2.0
                q01[i] = mid - min_range / 2.0
                q99[i] = mid + min_range / 2.0
                new_range = q99[i] - q01[i]
                logs.append(
                    f"  {key} dim {i:2d}: range {raw_range:.6e} -> {new_range:.6e} "
                    f"(q01: {mid - min_range/2:.6e}, q99: {mid + min_range/2:.6e})"
                )

    return result, logs


def main():
    parser = argparse.ArgumentParser(description="Post-process norm_stats.json to clamp narrow quantile ranges")
    parser.add_argument("--input", required=True, help="Path to input norm_stats.json")
    parser.add_argument("--output", required=True, help="Path to output norm_stats.json (can be same as input)")
    parser.add_argument("--min-range", type=float, default=0.1,
                        help="Minimum allowed q99-q01 range. Dimensions with narrower ranges will be expanded. (default: 0.1)")
    parser.add_argument("--dry-run", action="store_true",
                        help="Only print changes, don't write output")

    args = parser.parse_args()

    with open(args.input) as f:
        data = json.load(f)

    norm_stats = data["norm_stats"]
    modified_stats, logs = postprocess_norm_stats(norm_stats, min_range=args.min_range)

    if logs:
        print(f"Clamped {len(logs)} dimensions (min_range={args.min_range}):")
        for log in logs:
            print(log)
    else:
        print("No dimensions needed clamping.")

    if not args.dry_run:
        data["norm_stats"] = modified_stats
        with open(args.output, "w") as f:
            json.dump(data, f, indent=2)
            f.write("\n")
        print(f"\nSaved to: {args.output}")
    else:
        print("\n(dry-run, no file written)")


if __name__ == "__main__":
    main()
